import { Box, Text, useTheme, Flex, Container, HStack, Icon } from '@chakra-ui/react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { RiAuctionFill, RiArrowLeftLine, RiArrowRightLine } from 'react-icons/ri'
import { Nav } from '../components/Nav'
export default function Home() {
  const theme = useTheme()
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav/>
      <Container maxW='container.xl' my='5em'>
      <Flex flexWrap='wrap' flexDirection={'row'}  width={'100%'} >
        <Box  w={['100%', '100%', '100%', '60%']}  padding='2em'>
          <Text fontWeight={'bold'} fontSize={'5xl'}>Ubid Online Auction</Text>
          <Text fontSize={'3xl'} color='gray.600'>Discover, collect, and sell valuable items </Text>
          <HStack>
          <Link  passHref href={'/discover'}>
          <Box
            my={'20px'}
            display={'flex'}
            as='button'
            flexDirection={'row'}
            justifyContent={'center'}
            alignItems={'center'}
            width='220px'
            lineHeight='1.2'
            transition='0.4s ease'
            px='20px'
            py='20px'
            borderRadius='20px'
            
            bg='gray.100'
            color={theme.colors.black}
            _hover={{ transition: '0.4s ease', bg: theme.colors.gray[200], }}
            _active={{
              transform: 'scale(0.98)',
              borderColor: theme.colors.brand[100],
            }}
          >
           
              <Text >Discover</Text>
           
            <Icon ml='1em' as={RiArrowRightLine}/>
          </Box>
          </Link>
          <Link passHref href='/sign-up'>
          <Box
            as='button'
            width='220px'
            lineHeight='1.2'
            transition='0.4s ease'
            
            px='20px'
            py='20px'
            borderRadius='20px'
            
            bg='brand.500'
            color={theme.colors.white}
            _hover={{ transition: '0.4s ease', bg: theme.colors.brand[400], }}
            _active={{
              transform: 'scale(0.98)',
              borderColor: theme.colors.brand[100],
            }}
            _focus={{

            }}
          >
            Become a seller
          </Box>
          </Link>
          </HStack>

        </Box>
        <Box  w={['100%', '100%', '100%', '40%']}  padding='5%' display={'flex'} justifyContent={'center'} alignItems={'center'}>

            <Box maxWidth={400} width={'100%'} height={450} padding='2em' borderRadius={'20px'} background={'brand.100'}>
                <Box height={'85%'} width={'100%'} borderRadius={'16px'} display={'flex'} justifyContent={'center'} alignItems={'center'}  background={`linear-gradient(${theme.colors.white}, ${theme.colors.brand[200]})` }>
                <Icon w={200} h={200} color='brand.600' as={RiAuctionFill}/>
                </Box>
                <HStack>
                  <Box height={50} width={'80%'} my='1em' borderRadius={'12px'}  background={'brand.500'}/>
                  <Box height={50} width={50} my='1em' borderRadius={'100px'}  background={'brand.500'}/>
                </HStack>
            </Box>
            
        </Box>
      </Flex>
      </Container>
    </div>
  )
}
